### ISSUE TITLE
One's last test

### ISSUE THREAD

**Issue by Lesmiscore** [nao20010128nao/Issutter#10]
oneslast    
nintendoamerica    
5

**Comment by nao20010128nao** [comment]
Auto Message

```
Caught: groovy.lang.MissingMethodException: No signature of method: java.util.ArrayList.length() is applicable for argument types: () values: []
Possible solutions: last(), init(), init(), last(), get(int), get(int)
groovy.lang.MissingMethodException: No signature of method: java.util.ArrayList.length() is applicable for argument types: () values: []
Possible solutions: last(), init(), init(), last(), get(int), get(int)
	at twitter.run(twitter.groovy:111)

```

**Comment by nao20010128nao** [comment]
Auto Message

```
========== (1/20)
@NintendoAmerica Nintendo of America

A big thanks to all the Pokémon fans from development team members Mr. Ohmori & Mr. Iwao! #PokemonUltraSunMoon https://t.co/eNIzhTwFQ6

2017/12/01 10:24:55 JST
RT 249, Fav 1503
========== (2/20)
@NintendoAmerica Nintendo of America

From the courtroom to Elysium, check out this week’s Nintendo #eShop highlights! https://t.co/r7JvmfaZZG

2017/12/01 10:05:30 JST
RT 61, Fav 492
========== (3/20)
@NintendoVS Nintendo Versus

The mysterious Springtron is now a playable character with the #ARMS Ver. 4.1 update!

View full patch notes here:… https://t.co/nF47ka7Pam

2017/12/01 02:15:31 JST
RT 337, Fav 1685
========== (4/20)
@NintendoAmerica Nintendo of America

The “balloon” that ship is hanging from is actually a Titan named Argentum! This Titan is home to all kinds of incr… https://t.co/Hovc61C9TL

2017/12/01 04:00:11 JST
RT 271, Fav 1623
========== (5/20)
@animalcrossing Isabelle

Our first holiday event is here! Craft special furniture and decorate your campsite in festive colors. Happy holida… https://t.co/piJkyUKvqq

2017/12/01 02:45:04 JST
RT 1010, Fav 4029
========== (6/20)
@NintendoAmerica Nintendo of America

Make sure to grab a second set of Joy-Con controllers so you can challenge your friends and family in #ARMS right o… https://t.co/07fqLd8mnQ

2017/12/01 03:00:27 JST
RT 133, Fav 1186
========== (7/20)
@NintendoAmerica Nintendo of America

The votes have been tallied! Check out #MyNintendo members' most wished for holiday gifts. https://t.co/i9WYYZQTnW https://t.co/poIcUVjwLQ

2017/12/01 02:30:05 JST
RT 116, Fav 777
========== (8/20)
@NintendoAmerica Nintendo of America

Ready for #XenobladeChronicles2 tomorrow? A free Japanese-voice pack will be available day-one, & Expansion Pass ow… https://t.co/ugZEMt1C8d

2017/12/01 02:00:14 JST
RT 412, Fav 1753
========== (9/20)
@NintendoAmerica Nintendo of America

We can cerealously confirm that Kellogg’s Super Mario Cereal will be hitting store shelves on Dec. 11th!… https://t.co/ZHNerc7n5e

2017/12/01 00:15:11 JST
RT 9335, Fav 23490
========== (10/20)
@NintendoAmerica Nintendo of America

Need some help locating Power Moons or unlocking an outfit in #SuperMarioOdyssey? amiibo can help with that! Learn… https://t.co/n52Bu10YBV

2017/11/30 07:31:23 JST
RT 250, Fav 1585
========== (11/20)
@NintendoAmerica Nintendo of America

Grab your headphones and enjoy these song samples from the upcoming #XenobladeChronicles2 soundtrack!… https://t.co/0Xhxsqk0nD

2017/11/30 06:48:54 JST
RT 679, Fav 2093
========== (12/20)
@NintendoAmerica Nintendo of America

Since the franchise launched, 300 million @Pokemon video games have been sold - thank you! Adventures continue in… https://t.co/F3YPxtoNO5

2017/11/30 06:15:24 JST
RT 2332, Fav 9640
========== (13/20)
@NintendoAmerica Nintendo of America

Interested in the colorful cast of #XenobladeChronicles2? Check out this blog on the creation & design of the game’… https://t.co/dHjLgrdXfu

2017/11/30 02:04:02 JST
RT 568, Fav 2550
========== (14/20)
@NintendoAmerica Nintendo of America

The newest entry in the acclaimed #ShinMegamiTensei series is heading to #NintendoSwitch! Shin Megami Tensei V is c… https://t.co/o9ZJfcxftL

2017/11/30 00:30:11 JST
RT 2079, Fav 4635
========== (15/20)
@RE_Games Resident Evil

Resident Evil Revelations and Resident Evil Revelations 2 are out now for Nintendo Switch! Details:… https://t.co/Bb4MmHsMCS

2017/11/29 01:00:13 JST
RT 548, Fav 1812
========== (16/20)
@PA_Megacorp Penny Arcade

This year’s blind box has arrived, bringing with it a selection of 20 Super Mario Bros.™ 3 themed pins to delight a… https://t.co/pqtQYBTInJ

2017/11/29 07:15:15 JST
RT 616, Fav 2493
========== (17/20)
@NintendoAmerica Nintendo of America

Did you know that most buildings have thieves’ guild marks on them? You'll get a better idea as to what they mean i… https://t.co/R534uZC7pm

2017/11/29 05:47:52 JST
RT 213, Fav 1395
========== (18/20)
@NintendoAmerica Nintendo of America

They don’t come much tougher than Vandham. Leader of the Garfont Mercenaries, he fights in perfect sync with his Bl… https://t.co/xUvOqchPHd

2017/11/29 04:30:37 JST
RT 250, Fav 1435
========== (19/20)
@NintendoAmerica Nintendo of America

Here are the current top 8 contenders in the #Kirby Battle Royale Copy Ability Poll! Vote now, poll ends 12/2!… https://t.co/KULfO98alY

2017/11/29 03:30:04 JST
RT 410, Fav 1671
========== (20/20)
@NintendoAmerica Nintendo of America

Book II has been added to #FEHeroes! Clear Chapter 1: Part 5, and Fjorm will become your ally! More details here:… https://t.co/9S1WEA1fCH

2017/11/29 02:45:04 JST
RT 271, Fav 1220

```

**Comment by Lesmiscore** [comment]
Auto Message

```
========== (1/5)
@NintendoAmerica Nintendo of America

A big thanks to all the Pokémon fans from development team members Mr. Ohmori & Mr. Iwao! #PokemonUltraSunMoon https://t.co/eNIzhTwFQ6

2017/12/01 10:24:55 JST
RT 250, Fav 1504
========== (2/5)
@NintendoAmerica Nintendo of America

From the courtroom to Elysium, check out this week’s Nintendo #eShop highlights! https://t.co/r7JvmfaZZG

2017/12/01 10:05:30 JST
RT 61, Fav 492
========== (3/5)
@NintendoVS Nintendo Versus

The mysterious Springtron is now a playable character with the #ARMS Ver. 4.1 update!

View full patch notes here:… https://t.co/nF47ka7Pam

2017/12/01 02:15:31 JST
RT 337, Fav 1685
========== (4/5)
@NintendoAmerica Nintendo of America

The “balloon” that ship is hanging from is actually a Titan named Argentum! This Titan is home to all kinds of incr… https://t.co/Hovc61C9TL

2017/12/01 04:00:11 JST
RT 271, Fav 1623
========== (5/5)
@animalcrossing Isabelle

Our first holiday event is here! Craft special furniture and decorate your campsite in festive colors. Happy holida… https://t.co/piJkyUKvqq

2017/12/01 02:45:04 JST
RT 1010, Fav 4030

```

**Comment by nao20010128nao** [comment]
oneslast    
wakame186

**Comment by nao20010128nao** [comment]
oneslast    
wakame186

**Comment by nao20010128nao** [comment]
oneslast    
wakame186

**Comment by nao20010128nao** [comment]
oneslast    
wakame186

**Comment by nao20010128nao** [comment]
oneslast    
wakame186

**Comment by nao20010128nao** [comment]
oneslast    
wakame186

**Comment by nao20010128nao** [comment]
oneslast    
wakame186

**Comment by nao20010128nao** [comment]
Auto Message

```
Caught: 401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
message - Could not authenticate you.
code - 32

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=dbbd42aa or
	http://www.google.co.jp/search?q=09655fcd
TwitterException{exceptionCode=[dbbd42aa-09655fcd], statusCode=401, message=Could not authenticate you., code=32, retryAfter=-1, rateLimitStatus=null, version=4.0.6}
401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
message - Could not authenticate you.
code - 32

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=dbbd42aa or
	http://www.google.co.jp/search?q=09655fcd
TwitterException{exceptionCode=[dbbd42aa-09655fcd], statusCode=401, message=Could not authenticate you., code=32, retryAfter=-1, rateLimitStatus=null, version=4.0.6}
	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:164)
	at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
	at twitter4j.HttpClientBase.get(HttpClientBase.java:75)
	at twitter4j.TwitterImpl.get(TwitterImpl.java:1786)
	at twitter4j.TwitterImpl.getUserTimeline(TwitterImpl.java:144)
	at twitter4j.api.TimelinesResources$getUserTimeline.call(Unknown Source)
	at twitter.run(twitter.groovy:116)

```

**Comment by nao20010128nao** [comment]
Auto Message

```

```

**Comment by nao20010128nao** [comment]
Auto Message

```

```

**Comment by nao20010128nao** [comment]
Auto Message

```

```

**Comment by nao20010128nao** [comment]
Auto Message

```

```

**Comment by nao20010128nao** [comment]
oneslast    
wakame186

**Comment by nao20010128nao** [comment]
Auto Message

```
Caught: 401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
message - Could not authenticate you.
code - 32

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=dbbd42aa or
	http://www.google.co.jp/search?q=09655fcd
TwitterException{exceptionCode=[dbbd42aa-09655fcd], statusCode=401, message=Could not authenticate you., code=32, retryAfter=-1, rateLimitStatus=null, version=4.0.6}
401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
message - Could not authenticate you.
code - 32

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=dbbd42aa or
	http://www.google.co.jp/search?q=09655fcd
TwitterException{exceptionCode=[dbbd42aa-09655fcd], statusCode=401, message=Could not authenticate you., code=32, retryAfter=-1, rateLimitStatus=null, version=4.0.6}
	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:164)
	at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
	at twitter4j.HttpClientBase.get(HttpClientBase.java:75)
	at twitter4j.TwitterImpl.get(TwitterImpl.java:1786)
	at twitter4j.TwitterImpl.getUserTimeline(TwitterImpl.java:144)
	at twitter4j.api.TimelinesResources$getUserTimeline.call(Unknown Source)
	at twitter.run(twitter.groovy:116)

```

**Comment by Lesmiscore** [comment]
oneslast    
wakame186

**Comment by Lesmiscore** [comment]
Auto Message

```
========== (1/20)
@wakame186: わかめ

お風呂から上がってぽかぽかぽぽぽぽぽっぽぽｐ

2017/12/01 22:18:53 JST
RT 0, Fav 0
========== (2/20)
@wakame186: わかめ

ふろろ～

2017/12/01 21:56:31 JST
RT 0, Fav 0
========== (3/20)
@wakame186: わかめ

40番行ったみたい

2017/12/01 21:23:07 JST
RT 0, Fav 0
========== (4/20)
@wakame186: わかめ

ラベル貼らない？

2017/12/01 21:17:48 JST
RT 0, Fav 1
========== (5/20)
@wakame186: わかめ

10人もいる環境でテストできてないからか不調になったりする…

2017/12/01 20:57:33 JST
RT 0, Fav 0
========== (6/20)
@wakame186: わかめ

まったG+スパム判定くらったか？

2017/12/01 20:43:37 JST
RT 0, Fav 0
========== (7/20)
@wakame186: わかめ

intの最大値超えるんで…

2017/12/01 19:52:59 JST
RT 0, Fav 0
========== (8/20)
@kondo_orange: 近藤 悟(DO)/オレンジの人

いやぁ...(笑)
安いし絶対クソみたいな業務だこれ...
一太郎とか使えねぇわ！www
文科省、「プログラミング教育戦略マネージャー」採用を発表 | ICT教育ニュース https://t.co/hGuwQRp2LV

2017/12/01 17:51:10 JST
RT 5, Fav 5
========== (9/20)
@wakame186: わかめ

それは五郎丸や…

2017/12/01 17:28:30 JST
RT 1, Fav 0
========== (10/20)
@wakame186: わかめ

とっとこ～走るよ

2017/12/01 17:27:28 JST
RT 0, Fav 0
========== (11/20)
@wakame186: わかめ

Nice Bread.

2017/12/01 16:59:21 JST
RT 0, Fav 1
========== (12/20)
@wakame186: わかめ

体裁は整えてるんだけどね…

2017/12/01 16:44:18 JST
RT 0, Fav 0
========== (13/20)
@wakame186: わかめ

あーまじwebゴミデザイン…どうしよ…

2017/12/01 16:43:59 JST
RT 0, Fav 0
========== (14/20)
@joujinakata123: 中田譲治

正しいヘッドフォンの付け方。
こうすると音だけに集中し易いby 杉田

台本が読めないby 中田

こうしないとスタジオを壊してしまうby サイクロップス https://t.co/Hf68SoYHrZ

2017/12/01 15:54:43 JST
RT 13689, Fav 22081
========== (15/20)
@wakame186: わかめ

ちゅうもんはいりまーす

2017/12/01 15:32:00 JST
RT 0, Fav 0
========== (16/20)
@wakame186: わかめ

さてと…webも仕込んでいきますよ

2017/12/01 13:26:38 JST
RT 0, Fav 0
========== (17/20)
@wakame186: わかめ

あっ今日平日か

2017/12/01 13:22:56 JST
RT 0, Fav 0
========== (18/20)
@wakame186: わかめ

codebuilderとかmixerのやつとかどっかにまとめときたいけど、どこに書こうか……ワードプレスでも仕込むか？

2017/12/01 04:34:33 JST
RT 0, Fav 0
========== (19/20)
@wakame186: わかめ

ここまで作ったので寝ます https://t.co/yxczY5MFPS

2017/12/01 04:18:23 JST
RT 0, Fav 1
========== (20/20)
@wakame186: わかめ

@nkny1219 おやすみなさい！

2017/12/01 03:43:30 JST
RT 0, Fav 1

```
