### ISSUE TITLE
Query test

### ISSUE THREAD

**Issue by Lesmiscore** [nao20010128nao/Issutter#3]
mylast10

**Comment by nao20010128nao** [comment]
Auto Message

```
null
```

**Comment by nao20010128nao** [comment]
Auto Message

```
twitter.groovy failed.
```

**Comment by nao20010128nao** [comment]
Auto Message

```
Caught: java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
	at twitter4j.TwitterBaseImpl.ensureAuthorizationEnabled(TwitterBaseImpl.java:219)
	at twitter4j.TwitterBaseImpl.fillInIDAndScreenName(TwitterBaseImpl.java:132)
	at twitter4j.TwitterImpl.verifyCredentials(TwitterImpl.java:591)
	at twitter4j.api.UsersResources$verifyCredentials.call(Unknown Source)
	at twitter.run(twitter.groovy:82)

```

**Comment by nao20010128nao** [comment]
Auto Message

```
Caught: java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
	at twitter4j.TwitterBaseImpl.ensureAuthorizationEnabled(TwitterBaseImpl.java:219)
	at twitter4j.TwitterBaseImpl.fillInIDAndScreenName(TwitterBaseImpl.java:132)
	at twitter4j.TwitterImpl.verifyCredentials(TwitterImpl.java:591)
	at twitter4j.api.UsersResources$verifyCredentials.call(Unknown Source)
	at twitter.run(twitter.groovy:82)

```

**Comment by nao20010128nao** [comment]
Auto Message

```
Caught: java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
	at twitter4j.TwitterBaseImpl.ensureAuthorizationEnabled(TwitterBaseImpl.java:219)
	at twitter4j.TwitterBaseImpl.fillInIDAndScreenName(TwitterBaseImpl.java:132)
	at twitter4j.TwitterImpl.verifyCredentials(TwitterImpl.java:591)
	at twitter4j.api.UsersResources$verifyCredentials.call(Unknown Source)
	at twitter.run(twitter.groovy:82)

```

**Comment by nao20010128nao** [comment]
Auto Message

```
[TMUX_PANE:%10, PATH:/home/lesmi/bin:/home/lesmi/.local/bin:/home/lesmi/.linuxbrew/bin:/home/lesmi/go/bin:/home/lesmi/bin:/home/lesmi/.local/bin:/home/lesmi/.sdkman/candidates/groovy/current/bin:/home/lesmi/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games, LESSCLOSE:/usr/bin/lesspipe %s %s, SDKMAN_VERSION:5.5.13+272, MANPATH:/home/lesmi/.linuxbrew/share/man:/home/lesmi/.linuxbrew/share/man:, JAVA_HOME:/usr/lib/jvm/java-8-openjdk-amd64, TERM:screen, LANG:en_US.UTF-8, XDG_SESSION_ID:2, GROOVY_HOME:/home/lesmi/.sdkman/candidates/groovy/current, MAIL:/var/mail/lesmi, SDKMAN_DIR:/home/lesmi/.sdkman, LOGNAME:lesmi, PWD:/home/lesmi/Issutter, INFOPATH:/home/lesmi/.linuxbrew/share/info:/home/lesmi/.linuxbrew/share/info:, SDKMAN_CANDIDATES_DIR:/home/lesmi/.sdkman/candidates, _:./webhook.groovy, LANGUAGE:en_US:, SDKMAN_LEGACY_API:https://api.sdkman.io/1, SHELL:/bin/bash, LESSOPEN:| /usr/bin/lesspipe %s, SSH_TTY:/dev/pts/0, SSH_CLIENT:60.65.17.194 47008 22, SDKMAN_PLATFORM:Linux64, OLDPWD:/home/lesmi, USER:lesmi, SSH_CONNECTION:60.65.17.194 33420 160.16.138.59 22, TMUX:/tmp/tmux-1000/default,1371,0, LS_COLORS:rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:, XDG_RUNTIME_DIR:/run/user/1000, SDKMAN_CURRENT_API:https://api.sdkman.io/2, HOME:/home/lesmi, SHLVL:2]
Caught: java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
	at twitter4j.TwitterBaseImpl.ensureAuthorizationEnabled(TwitterBaseImpl.java:219)
	at twitter4j.TwitterBaseImpl.fillInIDAndScreenName(TwitterBaseImpl.java:132)
	at twitter4j.TwitterImpl.verifyCredentials(TwitterImpl.java:591)
	at twitter4j.api.UsersResources$verifyCredentials.call(Unknown Source)
	at twitter.run(twitter.groovy:84)

```

**Comment by nao20010128nao** [comment]
Auto Message

```
[TMUX_PANE:%10, PATH:/home/lesmi/bin:/home/lesmi/.local/bin:/home/lesmi/.linuxbrew/bin:/home/lesmi/go/bin:/home/lesmi/bin:/home/lesmi/.local/bin:/home/lesmi/.sdkman/candidates/groovy/current/bin:/home/lesmi/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games, LESSCLOSE:/usr/bin/lesspipe %s %s, SDKMAN_VERSION:5.5.13+272, MANPATH:/home/lesmi/.linuxbrew/share/man:/home/lesmi/.linuxbrew/share/man:, JAVA_HOME:/usr/lib/jvm/java-8-openjdk-amd64, TERM:screen, LANG:en_US.UTF-8, XDG_SESSION_ID:2, GROOVY_HOME:/home/lesmi/.sdkman/candidates/groovy/current, MAIL:/var/mail/lesmi, SDKMAN_DIR:/home/lesmi/.sdkman, LOGNAME:lesmi, PWD:/home/lesmi/Issutter, INFOPATH:/home/lesmi/.linuxbrew/share/info:/home/lesmi/.linuxbrew/share/info:, SDKMAN_CANDIDATES_DIR:/home/lesmi/.sdkman/candidates, _:./webhook.groovy, LANGUAGE:en_US:, SDKMAN_LEGACY_API:https://api.sdkman.io/1, SHELL:/bin/bash, LESSOPEN:| /usr/bin/lesspipe %s, SSH_TTY:/dev/pts/0, SSH_CLIENT:60.65.17.194 47008 22, SDKMAN_PLATFORM:Linux64, OLDPWD:/home/lesmi, USER:lesmi, SSH_CONNECTION:60.65.17.194 33420 160.16.138.59 22, TMUX:/tmp/tmux-1000/default,1371,0, LS_COLORS:rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:, XDG_RUNTIME_DIR:/run/user/1000, SDKMAN_CURRENT_API:https://api.sdkman.io/2, HOME:/home/lesmi, SHLVL:2]
Caught: java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
java.lang.IllegalStateException: Authentication credentials are missing. See http://twitter4j.org/en/configuration.html for details. See and register at http://apps.twitter.com/
	at twitter4j.TwitterBaseImpl.ensureAuthorizationEnabled(TwitterBaseImpl.java:219)
	at twitter4j.TwitterBaseImpl.fillInIDAndScreenName(TwitterBaseImpl.java:132)
	at twitter4j.TwitterImpl.verifyCredentials(TwitterImpl.java:591)
	at twitter4j.api.UsersResources$verifyCredentials.call(Unknown Source)
	at twitter.run(twitter.groovy:84)

```

**Comment by nao20010128nao** [comment]
Auto Message

```
Caught: java.io.FileNotFoundException: /home/lesmi/Issutter/Ptwitter4j.oauth.accessToken=870192233256964098-sKJGw8dkPHUgHyVG7VtgSFzEZg4aHJZ (/home/lesmi/Issutter/Ptwitter4j.oauth.accessToken=870192233256964098-sKJGw8dkPHUgHyVG7VtgSFzEZg4aHJZ)
java.io.FileNotFoundException: /home/lesmi/Issutter/Ptwitter4j.oauth.accessToken=870192233256964098-sKJGw8dkPHUgHyVG7VtgSFzEZg4aHJZ (/home/lesmi/Issutter/Ptwitter4j.oauth.accessToken=870192233256964098-sKJGw8dkPHUgHyVG7VtgSFzEZg4aHJZ)

```

**Comment by nao20010128nao** [comment]
Auto Message

```
Caught: java.io.FileNotFoundException: /home/lesmi/Issutter/Ptwitter4j.oauth.accessToken=870192233256964098-sKJGw8dkPHUgHyVG7VtgSFzEZg4aHJZ (/home/lesmi/Issutter/Ptwitter4j.oauth.accessToken=870192233256964098-sKJGw8dkPHUgHyVG7VtgSFzEZg4aHJZ)
java.io.FileNotFoundException: /home/lesmi/Issutter/Ptwitter4j.oauth.accessToken=870192233256964098-sKJGw8dkPHUgHyVG7VtgSFzEZg4aHJZ (/home/lesmi/Issutter/Ptwitter4j.oauth.accessToken=870192233256964098-sKJGw8dkPHUgHyVG7VtgSFzEZg4aHJZ)

```

**Comment by nao20010128nao** [comment]
Auto Message

```
========== (1/10)
@selecta_takuya TAKUYA the bringer

道路の白線を引く職人さんってかっこいい✨液体入ってるマシーンもかっこいい✨ https://t.co/XfwMpOPzh7

Caught: groovy.lang.MissingPropertyException: No such property: date for class: twitter4j.StatusJSONImpl
Possible solutions: lang, place
groovy.lang.MissingPropertyException: No such property: date for class: twitter4j.StatusJSONImpl
Possible solutions: lang, place
	at twitter$_run_closure1.doCall(twitter.groovy:28)
	at twitter$_run_closure5.doCall(twitter.groovy:87)
	at twitter.run(twitter.groovy:83)

```

**Comment by nao20010128nao** [comment]
Auto Message

```
========== (1/10)
@selecta_takuya TAKUYA the bringer

道路の白線を引く職人さんってかっこいい✨液体入ってるマシーンもかっこいい✨ https://t.co/XfwMpOPzh7

2017/12/01 15:49:21 JST
RT 3, Fav 10
========== (2/10)
@nokky246 のっきい@初音ミクシンフォニー東京

最近の初音ミクの公式の動向を見ていると、何とかバランスを保とうとしている感。
マジミラや #初音ミクsings で流暢にしゃべらせ人間ぽくしたかと思えば #名作くん でロボットとして登場させる。
#初音ミクシンフォニー で格式高く… https://t.co/v8WWb2AEud

2017/11/30 23:08:03 JST
RT 41, Fav 52
========== (3/10)
@Kuroyakko_9685 くろやっこ

1999年の夏。今から18年も前のことですが…。
品川駅に突如として現れたこの茶色い103系にピンときたら、是非ともRTをください。
「懐かしい！」「そういえばあったねー」なんて、思いを巡らせてくだされば幸いです。
若い方は「なん… https://t.co/MfFekzlNQC

2017/12/01 11:07:00 JST
RT 286, Fav 287
========== (4/10)
@yuruhuwa_kdenpa ゆるふわ怪電波☆埼玉

我が国には「█す」の代わりにこの言葉がある https://t.co/B5fTFsiLdN

2017/12/01 10:13:37 JST
RT 661, Fav 979
========== (5/10)
@gutigFaxe HAL

半年前からいるSE「僕がやっても10日かかります」
上司「じゃあ10人いたら1日で終わるよね？」

翌日、何も知識のない素人10人ドーン

上司「じゃあ彼らの管理と教育も含めてよろ」

 #IT業界クソ現場オブザイヤー2017

2017/11/30 19:44:30 JST
RT 3052, Fav 2373
========== (6/10)
@NintendoAmerica Nintendo of America

We can cerealously confirm that Kellogg’s Super Mario Cereal will be hitting store shelves on Dec. 11th!… https://t.co/ZHNerc7n5e

2017/12/01 00:15:11 JST
RT 9257, Fav 23248
========== (7/10)
@DOGHOUSE_srv クロ執事＠犬小屋

社労士「過労で鬱が出てるから残業禁止」
上司「納期の方が大事」

#IT業界クソ現場オブザイヤー2017

2017/11/30 08:20:08 JST
RT 139, Fav 76
========== (8/10)
@signa_11 シンゴ

#IT業界クソ現場オブザイヤー2017

キックオフミーティングで
「もう着手してることになってる」
「要件は未確定」
「見積が高いと言われ受注は未済」
「でもなぜか納品日は決まってる」Σ(ﾟдﾟ；)
「受注前なので増員不可」Σ… https://t.co/80ONXqIX6e

2017/11/30 17:33:13 JST
RT 38, Fav 33
========== (9/10)
@k1ak2ok3ok4i シメサバ

#IT業界クソ現場オブザイヤー2017
↓ITで発覚した障害の原因↓
//分からなかったので実装しなかったです

2017/11/29 23:01:12 JST
RT 69, Fav 65
========== (10/10)
@city_swimmer トビウオ師匠

A「私がミスしたけど始末書は君の名前で出すよ まっ君も後々の勉強になると思えば儲けものｗ」
私「は？」
上の人「虚偽報告？」
A「こいつがやったことにすれば役立たずが出ていくだけで丸く収まるんだよｗ私がいなくなるのは損失だよ？ｗ」
#IT業界クソ現場オブザイヤー2017

2017/12/01 01:32:21 JST
RT 122, Fav 77

```

**Comment by Lesmiscore** [comment]
Auto Message

```
========== (1/10)
@2ndLesmi Inversed nao20010128nao

自分のツイート出すのは出来た

2017/12/01 17:06:52 JST
RT 0, Fav 0
========== (2/10)
@selecta_takuya TAKUYA the bringer

道路の白線を引く職人さんってかっこいい✨液体入ってるマシーンもかっこいい✨ https://t.co/XfwMpOPzh7

2017/12/01 15:49:21 JST
RT 3, Fav 10
========== (3/10)
@nokky246 のっきい@初音ミクシンフォニー東京

最近の初音ミクの公式の動向を見ていると、何とかバランスを保とうとしている感。
マジミラや #初音ミクsings で流暢にしゃべらせ人間ぽくしたかと思えば #名作くん でロボットとして登場させる。
#初音ミクシンフォニー で格式高く… https://t.co/v8WWb2AEud

2017/11/30 23:08:03 JST
RT 41, Fav 52
========== (4/10)
@Kuroyakko_9685 くろやっこ

1999年の夏。今から18年も前のことですが…。
品川駅に突如として現れたこの茶色い103系にピンときたら、是非ともRTをください。
「懐かしい！」「そういえばあったねー」なんて、思いを巡らせてくだされば幸いです。
若い方は「なん… https://t.co/MfFekzlNQC

2017/12/01 11:07:00 JST
RT 286, Fav 290
========== (5/10)
@yuruhuwa_kdenpa ゆるふわ怪電波☆埼玉

我が国には「█す」の代わりにこの言葉がある https://t.co/B5fTFsiLdN

2017/12/01 10:13:37 JST
RT 661, Fav 980
========== (6/10)
@gutigFaxe HAL

半年前からいるSE「僕がやっても10日かかります」
上司「じゃあ10人いたら1日で終わるよね？」

翌日、何も知識のない素人10人ドーン

上司「じゃあ彼らの管理と教育も含めてよろ」

 #IT業界クソ現場オブザイヤー2017

2017/11/30 19:44:30 JST
RT 3060, Fav 2379
========== (7/10)
@NintendoAmerica Nintendo of America

We can cerealously confirm that Kellogg’s Super Mario Cereal will be hitting store shelves on Dec. 11th!… https://t.co/ZHNerc7n5e

2017/12/01 00:15:11 JST
RT 9258, Fav 23256
========== (8/10)
@DOGHOUSE_srv クロ執事＠犬小屋

社労士「過労で鬱が出てるから残業禁止」
上司「納期の方が大事」

#IT業界クソ現場オブザイヤー2017

2017/11/30 08:20:08 JST
RT 139, Fav 76
========== (9/10)
@signa_11 シンゴ

#IT業界クソ現場オブザイヤー2017

キックオフミーティングで
「もう着手してることになってる」
「要件は未確定」
「見積が高いと言われ受注は未済」
「でもなぜか納品日は決まってる」Σ(ﾟдﾟ；)
「受注前なので増員不可」Σ… https://t.co/80ONXqIX6e

2017/11/30 17:33:13 JST
RT 38, Fav 33
========== (10/10)
@k1ak2ok3ok4i シメサバ

#IT業界クソ現場オブザイヤー2017
↓ITで発覚した障害の原因↓
//分からなかったので実装しなかったです

2017/11/29 23:01:12 JST
RT 69, Fav 65

```
